apiVersion: v2
type: application
name: sftpgo
version: 0.20.3
appVersion: 2.5.4
kubeVersion: ">=1.16.0-0"
description: Fully featured and highly configurable SFTP server with optional FTP/S and WebDAV support.
keywords:
  - sftp
  - ftp
  - webdav
home: https://github.com/drakkan/sftpgo
sources:
  - https://github.com/drakkan/sftpgo
  - https://github.com/uvoo/charts/tree/main/charts/sftpgo
maintainers:
  - name: Jeremy Busk 
    email: jeremybusk@gmail.com
    url: https://www.uvoo.io
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Updated sftpgo to 2.5.4
  artifacthub.io/images: |
    - name: sftpgo
      image: ghcr.io/drakkan/sftpgo:v2.5.4
    - name: sftpgo-alpine
      image: ghcr.io/drakkan/sftpgo:v2.5.4-alpine
